<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>fileTypes</key>
<array>
  <string>rist</string>
</array>

<key>name</key>
<string>RistLang</string>

<key>scopeName</key>
<string>source.rist</string>

<key>patterns</key>
<array>
  <dict>
    <key>include</key>
    <string>#invalids</string>
  </dict>
  <dict>
    <key>include</key>
    <string>#utils</string>
  </dict>
  <dict>
    <key>include</key>
    <string>#operators</string>
  </dict>
</array>

<key>repository</key>
<dict>

<key>invalids</key>
<dict>

  <key>patterns</key>
  <array>
    <dict>
      <key>match</key>
      <string>((def(?!(ine)))|from|import|async)</string>
      <key>name</key>
      <string>invalid.illegal</string>
    </dict>
    <dict>
      <key>match</key>
      <string>((//.*$(?&lt;!(;)))|(.?(?!(;))$)(?&lt;!(;)))</string>
      <key>name</key>
      <string>invalid.illegal</string>
      <key>comment</key>
      <string>Line should must end with ";"</string>
    </dict>
  </array>
</dict>

<key>utils</key>
<dict>
  <key>patterns</key>
  <array>
    <dict>
      <key>match</key>
      <string>//.*</string>
      <key>name</key>
      <string>comment.line.double-slash</string>
    </dict>
    <dict>
      <key>match</key>
      <string>([\d]+)</string>
      <key>name</key>
      <string>constant.numeric</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(True|False)</string>
      <key>name</key>
      <string>constant.language</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(print|input|super|self|cls)</string>
      <key>name</key>
      <string>variable.language</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(int|str|bool|type|dict)</string>
      <key>name</key>
      <string>storage.type</string>
    </dict>
  </array>
</dict>

<key>operators</key>
<dict>
  <key>patterns</key>
  <array>
    <dict>
      <key>match</key>
      <string>((a fn \=\=\>([ \t]+))?((define)(?=[ \t]+[a-zA-Z0-9_]*[ \t]*[\{])))</string>

      <key>name</key>
      <string>keyword.operator</string>
    </dict>
    <dict>
      <key>match</key>
      <string>((or|class|an|while|for|in|if|elif|else|as|global|nonlocal|match|case)(?=( )))</string>

      <key>name</key>
      <string>keyword.operator</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(return|break|continue|((else|try|except|finally)?=(\:)))</string>

      <key>name</key>
      <string>keyword.operator</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(\+@|@\+|\|\||\||__(//|&lt;|&gt;)|/|\=(?!(\>|\-))|\+|\-(?!(\=\>))|\*|\:|\.\.(\.)?|\;|\!\=)</string>

      <key>name</key>
      <string>keyword.operator</string>
    </dict>
    <dict>
      <key>match</key>
      <string>([a-zA-Z0-9_]*(\{)|\})</string>
      <key>name</key>
      <string>entity.name.function</string>
    </dict>
  </array>
</dict>

</dict>
</dict>
</plist>
